---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html
- hosts: all
  pre_tasks:
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# Update packages on all hosts
# apt --help
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: yes
      become: yes

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# Selfhosted hosts roles
  roles:
    - role: installation
      dir: './'

# # https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change
# # Selfhosted hosts handlers
#   handlers:
#     - include_tasks: './handlers/main.yml'
