---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html
- hosts: all
  pre_tasks:
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# Update packages on all hosts
# apt --help
    - name: Update packages
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: yes
      become: yes
      tags:
        - packages
        - pre

# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html
# Selfhosted hosts roles
  roles:
    - role: tsukune_ch.canonical_livepatch
      vars:
        canonical_livepatch_token: "{{ lookup('env', 'CANONICAL_KEY') }}"
      become: yes
      tags:
        - canonical

    - role: geerlingguy.ntp
      vars:
        ntp_enabled: true
        ntp_timezone: Europe/Paris
      become: yes
      tags:
        - ntp

    - role: install
      dir: '/app'
      tags:
        - main
