---
- hosts: all
  become: yes
  roles:
    - { role: common, dir: '/app' }
  tasks:
    - name: Update packages
      apt:
        autoclean: yes
        autoremove: yes
        update_cache: yes
        upgrade: yes
