# https://docs.ansible.com/ansible/latest/modules/snap_module.html
# Install a snap with classic confinement
- name: Install canonical livepatch snap
  snap:
    name: canonical-livepatch
    classic: no
  become: yes

# https://docs.ansible.com/ansible/latest/modules/command_module.html#command-module
- name: Check livepatch status
  command: /snap/bin/canonical-livepatch status --verbose
  register: livepatch

# https://docs.ansible.com/ansible/latest/modules/command_module.html
# https://auth.livepatch.canonical.com/?user_type=ubuntu-user
- name: Enable canonical livepatch
  command: "/snap/bin/canonical-livepatch enable {{ lookup('env', 'CANONICAL_KEY') }}"
  become: yes
  when: livepatch is defined and livepatch.rc is defined and livepatch.rc != 0

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
# iwlist --help
# https://manpages.debian.org/stretch/wireless-tools/iwlist.8.en.html
# https://askubuntu.com/questions/463486/can-no-longer-use-screen-share-to-connect-mac-to-ubuntu-since-upgrading-to-14-04#comment982480_463697
- name: Install remote desktop sharing and wifi tools packages
  apt:
    pkg:
    - vino
    - wireless-tools
    - hwinfo
    - python3-psutil
  become: yes

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# parsec tasks file for shokohscrole
- name: Parsec tasks
  import_tasks: parsec.yml

# # https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# # edimax usb wifi tasks file for shokohscrole
# - name: Edimax tasks
#   import_tasks: edimax.yml

# https://docs.ansible.com/ansible/latest/modules/docker_network_module.html
# http://www.subnet-calculator.com/subnet.php?net_class=B
- name: Define docker lucio network
  docker_network:
    name: lucio
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"

# # https://docs.ansible.com/ansible/latest/modules/sysctl_module.html
# # https://github.com/prometheus/node_exporter#disabled-by-default
# - name: System performance access
#   sysctl:
#     name: kernel.perf_event_paranoid
#     value: '0'
#   become: yes

# # https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# # probes tasks file for shokohscrole
# - name: Probes tasks
#   import_tasks: ../probes.yml
#   vars:
#     docker_network: lucio
#     cadvisor_image: gcr.io/google-containers/cadvisor
#     filebeat_image: 'docker.elastic.co/beats/filebeat:{{ elk_version }}'

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# traefik tasks file for shokohscrole
- name: Traefik tasks
  import_tasks: ../traefik.yml
  vars:
    docker_network: lucio

# # https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# # developer tasks file for shokohscrole
# - name: Developer dependency tasks
#   import_tasks: developer.yml
#   vars:
#     docker_network: lucio

# # https://docs.ansible.com/ansible/latest/modules/import_role_module.html
# - name: Import wifi role
#   include_role:
#     name: layereight.wifi
#   vars:
#     wifi_ssid: "{{ wifi_default_ssid }}"
#     wifi_psk: lookup('env', 'WIFI_PASSWORD')
#     wifi_country: "{{ wifi_default_country }}"
#     wifi_disable_dhcpcd_workaround: "{{ wifi_default_disable_dhcpcd_workaround }}"
#     wifi_disable_dhcpcd_workaround_interface: "{{ wifi_default_disable_dhcpcd_workaround_interface }}"

# https://docs.ansible.com/ansible/latest/modules/dconf_module.html
# https://vastiny.com/post/tech/ubuntu-screen-sharing
# https://askubuntu.com/questions/12206/how-do-i-start-the-vnc-server
- name: Vino server
  import_tasks: remote-desktop.yml

# https://docs.ansible.com/ansible/latest/modules/import_role_module.html
# https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04
# https://github.com/arillso/ansible.logrotate
- name: Import logrotate role
  include_role:
    name: arillso.logrotate
  vars:
    logrotate_options:
      - daily
      - rotate 2
      - create
      - dateext
      - su root syslog
