---
# defaults file for shokohscrole
home_subnet: 10.0.42.0/24

gateway_addr: 1
vip_addr: 42
sombra_addr: 60
lucio_addr: 70
zarya_addr: 80
pi_addr: 90

keepalived:
  sombra:
    state: BACKUP
    priority: 102
  lucio:
    state: BACKUP
    priority: 101
  zarya:
    state: BACKUP
    priority: 100
