# handlers file for shokohscrole
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change
---
# https://docs.ansible.com/ansible/latest/modules/reboot_module.html
# https://earlruby.org/2019/07/rebooting-a-host-with-ansible/
- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: yes
