# sombra tasks file for shokohscrole
---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
# https://wiki.debian.org/NTFS
- name: Install zip, NTFS and exFAT packages
  apt:
    pkg:
    - ntfs-3g
    - exfat-utils
    - zip
  become: yes

# https://docs.ansible.com/ansible/latest/modules/mount_module.html
# lsblk -f to show disks connected and filesystems used
- name: Mount External disks
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: mounted
  with_items:
      - { path: '/mnt/WD1To', src: '/dev/sda2', fstype: 'ntfs', opts: 'auto,uid=1000,gid=1000,umask=0000' }
      - { path: '/mnt/WD2To', src: '/dev/sdb1', fstype: 'exfat', opts: 'auto,uid=1000,gid=1000,umask=0000' }
  become: yes

# https://docs.ansible.com/ansible/latest/modules/openssh_keypair_module.html
- name: Generate ssh key
  openssh_keypair:
    path: '/home/{{ ansible_user }}/.ssh/id_rsa'

# https://docs.ansible.com/ansible/latest/modules/stat_module.html
# Determine if lab folder path exists
- name: Stat lab folder
  stat:
    path: '/home/{{ ansible_user }}/seedbox'
  register: lab_repo_folder

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://github.com/docker/compose/issues/3851#issuecomment-240941586
- name: Add COMPOSE_HTTP_TIMEOUT environment variable
  lineinfile:
    path: '/home/{{ ansible_user }}/.bashrc'
    line: 'export COMPOSE_HTTP_TIMEOUT=300'

# https://docs.ansible.com/ansible/latest/modules/git_module.html
# Clone selfhosted docker-compose repo
- name: Clone lab repo
  git:
    repo: https://github.com/shokohsc/essbey.git
    dest: '/home/{{ ansible_user }}/seedbox'
  when: lab_repo_folder is defined and not lab_repo_folder.stat.exists

# https://docs.ansible.com/ansible/latest/modules/sysctl_module.html
# https://www.elastic.co/guide/en/elasticsearch/reference/7.5/docker.html#docker-prod-prerequisites
# Elasticsearch container requirement
- name: System VM maximum map count
  sysctl:
    name: vm.max_map_count
    value: '262144'
  become: yes


# https://docs.ansible.com/ansible/latest/modules/sysctl_module.html
# https://unix.stackexchange.com/questions/520625/transmission-daemon-udp-failed-to-set-receive-send-buffer
# Transmission container requirement
- name: 16 MiB for the receive buffer
  sysctl:
      name: net.core.rmem_max
      value: '16777216'
  become: yes

# https://docs.ansible.com/ansible/latest/modules/sysctl_module.html
# https://unix.stackexchange.com/questions/520625/transmission-daemon-udp-failed-to-set-receive-send-buffer
# Transmission container requirement
- name: 4 MiB for send buffer
  sysctl:
      name: net.core.wmem_max
      value: '4194304'
  become: yes

# https://docs.ansible.com/ansible/latest/modules/file_module.html
# Readable docker volume files
- name: Recursively change permissions of a directory
  file:
    path: /var/lib/docker
    state: directory
    # recurse: yes
    mode: '0755'
  become: yes
