# cloudflared tasks file for shokohscrole
# https://docs.pi-hole.net/guides/dns-over-https/
# https://github.com/crazy-max/docker-cloudflared
# https://github.com/crazy-max/docker-cloudflared/blob/master/examples/pihole/docker-compose.yml
---
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: Cloudflared docker container
  docker_container:
    image: crazymax/cloudflared:latest
    name: cloudflared
    hostname: cloudflared
    networks:
      - name: pihole
        ipv4_address: 172.1.0.63
    ports:
      - '49312:49312/tcp'
    env:
      TZ: Europe/Paris
      TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
    restart: unless-stopped
    log_driver: json-file
    log_options:
      max-size: '50k'
      max-file: '2'
