# cloudflared tasks file for shokohscrole
# https://docs.pi-hole.net/guides/dns-over-https/
# https://github.com/crazy-max/docker-cloudflared
# https://github.com/crazy-max/docker-cloudflared/blob/master/examples/pihole/docker-compose.yml
---
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: Cloudflared docker container
  docker_container:
    image: crazymax/cloudflared:latest
    pull: true
    name: cloudflared
    hostname: cloudflared
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: pihole
        ipv4_address: 172.2.0.63
    ports:
      - '49312:49312/tcp'
    etc_hosts:
      dns.google: 8.8.8.8
    env:
      TZ: Europe/Paris
      TUNNEL_DNS_UPSTREAM: https://dns.google/dns-query,https://1.1.1.1/dns-query
    restart_policy: unless-stopped
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
