# parsec tasks file for shokohscrole
# https://support.parsecgaming.com
---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
# https://parsecgaming.com/downloads/
- name: Install xbox driver
  apt:
    pkg:
      - xboxdrv
      - xz-utils
  become: yes
  tags:
    - parsec
    - pi

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
# https://parsecgaming.com/downloads/
- name: Install parsec-linux.deb package from the parsecgaming.com
  apt:
    deb: https://s3.amazonaws.com/parsec-build/package/parsec-rpi.deb
  become: yes
  tags:
    - parsec
    - pi

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://support.parsecgaming.com/hc/en-us/articles/115003035491-Finding-Your-Peer-ID
- name: Add parsec alias
  lineinfile:
    path: '/home/{{ ansible_user }}/.bashrc'
    line: "alias parsec='DISPLAY=:0 parsecd app_daemon=0:peer_id={{ lookup('env', 'PARSEC_PEER_ID') }}:encoder_bitrate=50:network_try_lan=1:client_vsync=1:client_fullscreen=0:client_windowed=0:client_window_x=1920:client_window_y=1080:client_overlay=0:decoder_software=0:client_audio_buffer=100000:server_admin_mute=0'"
  tags:
    - parsec
    - pi

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html
# https://support.parsecgaming.com/hc/en-us/articles/360001562772-All-Advanced-Configuration-Options
- name: Parsec client configuration
  lineinfile:
    create: yes
    path: '/home/{{ ansible_user }}/.parsec/config.txt'
    line: '{{ item.line }}'
    regexp: '{{ item.regex }}'
  with_items:
    - { line: 'app_daemon=0', regex: '^app_daemon='}
    - { line: 'encoder_bitrate=50', regex: '^encoder_bitrate='}
    - { line: 'network_try_lan=1', regex: '^network_try_lan='}
    - { line: 'client_vsync=1', regex: '^client_vsync='}
    - { line: 'client_fullscreen=0', regex: '^client_fullscreen='}
    - { line: 'client_windowed=0', regex: '^client_windowed='}
    - { line: 'client_window_x=1920', regex: '^client_window_x='}
    - { line: 'client_window_y=1080', regex: '^client_window_y='}
    - { line: 'client_overlay=0', regex: '^client_overlay='}
    - { line: 'decoder_software=0', regex: '^decoder_software='}
    - { line: 'client_audio_buffer=100000', regex: '^client_audio_buffer='}
    - { line: 'server_admin_mute=0', regex: '^server_admin_mute='}
  tags:
    - parsec
    - pi

# https://docs.ansible.com/ansible/latest/modules/command_module.html
# https://stackoverflow.com/questions/43015536/xhost-command-for-docker-gui-apps-eclipse
- name: Allow X server access to docker
  command: /usr/bin/xhost local:root
  environment:
    DISPLAY: "unix:0"
  tags:
    - parsec
    - pi

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
# https://www.raspberrypi.org/documentation/remote-access/samba.md
- name: Install samba dependencies
  apt:
    pkg:
    - samba
    - samba-common-bin
    - smbclient
    - cifs-utils
  become: yes
  tags:
    - samba
    - pi

# https://docs.ansible.com/ansible/2.9/modules/file_module.html
- name: Create samba directory
  file:
    path: /home/{{ ansible_user }}/samba
    state: directory
    mode: '0755'
  tags:
    - samba
    - pi

# # https://docs.ansible.com/ansible/latest/modules/mount_module.html
# # lsblk -f to show disks connected and filesystems used
# - name: Mount External disks
#   mount:
#     path: '{{ item.path }}'
#     src: '{{ item.src }}'
#     fstype: '{{ item.fstype }}'
#     state: '{{ item.state }}'
#   with_items:
#       - { path: '/home/{{ ansible_user }}/samba', src: '//shokohsc.home/shared', fstype: 'cifs', state: 'mounted' }
#   become: yes
#   tags:
#     - samba
#     - pi
