# unbound tasks file for shokohscrole
# https://docs.pi-hole.net/guides/unbound/
# https://github.com/pi-hole/docker-pi-hole/issues/378
# https://hub.docker.com/r/mvance/unbound
# https://github.com/chriscrowe/docker-pihole-unbound
---
# https://docs.ansible.com/ansible/latest/modules/template_module.html
# https://www.mydailytutorials.com/ansible-template-module-examples/
# https://jinja.palletsprojects.com/en/2.10.x/
- name: Template unbound config file
  template:
    src: unbound/a-records.conf.j2
    dest: "/home/{{ ansible_user }}/pihole/unbound/a-records.conf"
  become: yes

# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: Unbound docker container
  docker_container:
    image: mvance/unbound:latest
    pull: true
    name: unbound
    hostname: unbound
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: pihole
        ipv4_address: 172.1.0.83
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    volumes:
      - "/home/{{ ansible_user }}/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf:ro"
    restart_policy: unless-stopped
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
