# main tasks file for shokohscrole
---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - vim
    - exfat-utils
    - nfs-common
  become: yes
  tags:
    - packages

# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  become: yes
  tags:
    - swap
    - fstab

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: yes
  tags:
    - swap

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# ls --help (hidden files, list view, append indicator entries, Human readable sizes)
- name: Add 'll' alias & edit PATH environment variable
  lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
  with_items:
    - { path: '/home/{{ ansible_user }}/.bashrc', line: "alias ll='ls -AlFh'" }
    - { path: '/home/{{ ansible_user }}/.bashrc', line: 'export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' }
  tags:
    - user

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: Set ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  tags:
    - sysctl

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: Set ipv4 forwarding
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - { name: 'net.core.wmem_max', value: '1048576' } # default 212992
    - { name: 'net.core.rmem_max', value: '4194304' } # default 212992
  tags:
    - sysctl

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://blaszkowski.com/2018/09/02/ansible-add-user-to-sudo
- name: Add user to sudoers
  lineinfile:
    path: '/etc/sudoers.d/{{ ansible_user }}'
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    mode: '0440'
    create: yes
    validate: '/usr/sbin/visudo -cf %s'
  become: yes
  tags:
    - user

# https://docs.ansible.com/ansible/latest/modules/cron_module.html
- name: Set cron job to update packages monthly
  cron:
    name: apt packages monthly updater
    minute: '0'
    hour: '0'
    day: '1'
    job: 'apt update && apt upgrade'
  become: yes
  tags:
    - packages
    - cron

# https://docs.ansible.com/ansible/latest/modules/mount_module.html
# lsblk -f to show disks connected and filesystems used
- name: Mount External disks
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: '{{ item.state }}'
  with_items:
      - { path: '/mnt/ssd', src: '/dev/disk/by-uuid/1984739c-9adf-4a2f-89df-bbe61dbf381a', fstype: 'ext4', opts: 'defaults', state: 'absent' }
  become: yes
  when: ansible_facts['nodename']|lower == 'sombra'
  tags:
    - disk
    - nfs
    - fstab

# https://docs.ansible.com/ansible/latest/modules/mount_module.html
# lsblk -f to show disks connected and filesystems used
- name: Mount External disks
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: '{{ item.state }}'
  with_items:
      - { path: '/mnt/ssd', src: '/dev/disk/by-uuid/c8a8e31d-916d-4e7f-b9ea-e2b9c94e3d93', fstype: 'ext4', opts: 'defaults', state: 'absent' }
      - { path: '/mnt/WD1To', src: '/dev/disk/by-uuid/6096AA2B96AA0220', fstype: 'ntfs', opts: 'rw,uid=1000,gid=1000,dmask=0002,fmask=0003,exec,suid,permissions', state: 'mounted' }
  become: yes
  when: ansible_facts['nodename']|lower == 'lucio'
  tags:
    - disk
    - nfs
    - fstab

# https://docs.ansible.com/ansible/latest/modules/mount_module.html
# lsblk -f to show disks connected and filesystems used
- name: Mount External disks
  mount:
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts }}'
    state: '{{ item.state }}'
  with_items:
      - { path: '/mnt/ssd', src: '/dev/disk/by-uuid/ddcc3270-3831-4af1-a266-0e57f2b8c4fd', fstype: 'ext4', opts: 'defaults', state: 'absent' }
      - { path: '/mnt/WD2To', src: '/dev/disk/by-uuid/FC3D-B257', fstype: 'exfat', opts: 'rw,uid=1000,gid=1000,dmask=0002,fmask=0003,exec,suid,permissions', state: 'mounted' }
  become: yes
  when: ansible_facts['nodename']|lower == 'zarya'
  tags:
    - disk
    - nfs
    - fstab
