# main tasks file for shokohscrole
---
# https://docs.ansible.com/ansible/latest/modules/apt_module.html
# apt --help
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - vim
    - exfat-utils
    - nfs-common
  become: yes
  tags:
    - packages
    - nucs
    - pi

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# ls --help (hidden files, list view, append indicator entries, Human readable sizes)
- name: Add 'll' alias & edit PATH environment variable
  lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
  with_items:
    - { path: '/home/{{ ansible_user }}/.bashrc', line: "alias ll='ls -AlFh'" }
    - { path: '/home/{{ ansible_user }}/.bashrc', line: 'export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' }
  tags:
    - user
    - nucs
    - pi

# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
# https://blaszkowski.com/2018/09/02/ansible-add-user-to-sudo
- name: Add user to sudoers
  lineinfile:
    path: '/etc/sudoers.d/{{ ansible_user }}'
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
    mode: '0440'
    create: yes
    validate: '/usr/sbin/visudo -cf %s'
  become: yes
  tags:
    - user
    - nucs
    - pi

# https://docs.ansible.com/ansible/latest/modules/cron_module.html
- name: Set cron job to update packages monthly
  cron:
    name: apt packages monthly updater
    minute: '0'
    hour: '0'
    day: '1'
    job: 'apt update && apt upgrade'
  become: yes
  tags:
    - packages
    - cron
    - nucs
    - pi

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# nucs specific tasks file for shokohscrole
- name: Nucs tasks
  import_tasks: nucs.yml
  when: ansible_facts['nodename']|lower != 'pi'

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# pi specific tasks file for shokohscrole
- name: Pi tasks
  import_tasks: raspberrypi/raspberrypi.yml
  when: ansible_facts['nodename']|lower == 'pi'
