# common nucs tasks file for shokohscrole
---
# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# sombra specific tasks file for shokohscrole
- name: Sombra tasks
  import_tasks: sombra/sombra.yml
  when: ansible_facts['nodename']|lower == 'sombra'

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# pihole specific tasks file for shokohscrole
- name: Pihole tasks
  import_tasks: sombra/pihole.yml
  when: ansible_facts['nodename']|lower == 'sombra'

# https://docs.ansible.com/ansible/latest/modules/import_tasks_module.html
# lucio specific tasks file for shokohscrole
- name: Lucio tasks
  import_tasks: lucio/lucio.yml
  when: ansible_facts['nodename']|lower == 'lucio'
