# common nucs tasks file for shokohscrole
---
# https://docs.ansible.com/ansible/2.9/modules/apt_module.html
# apt --help
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - haproxy
    - keepalived
  become: yes
  tags:
    - packages
    - haproxy
    - keepalived
    - nucs

# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  become: yes
  tags:
    - swap
    - fstab
    - nucs

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  become: yes
  tags:
    - swap
    - nucs

- name: Remove swap file
  file:
    path: /swap.img
    state: absent
  become: yes
  tags:
    - swap
    - nucs

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: Set ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  tags:
    - sysctl
    - nucs

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: Set ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  tags:
    - sysctl
    - nucs

# Set net core memory settings -> transmission
- name: Set net core memory
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - { name: 'net.core.wmem_max', value: '1048576' } # default 212992
    - { name: 'net.core.rmem_max', value: '4194304' } # default 212992
  tags:
    - sysctl
    - nucs

# Set virtual memory -> elasticsearch
- name: Set net core memory
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - { name: 'vm.max_map_count', value: '262144' } # default 65530
  tags:
    - sysctl
    - nucs

# Set max user watches -> plex
- name: Set max user watches
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - { name: 'fs.inotify.max_user_watches', value: '524288' } # default 8192
    - { name: 'fs.inotify.max_user_instances', value: '524288' } # default 8192
  tags:
    - sysctl
    - nucs

# Set so max conn -> redis
- name: Set max user watches
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  become: yes
  with_items:
    - { name: 'net.core.somaxconn', value: '65535' } # default 128
  tags:
    - sysctl
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/template_module.html
# https://www.mydailytutorials.com/ansible-template-module-examples/
# https://jinja.palletsprojects.com/en/2.10.x/
- name: Template keepalived config file
  template:
    src: keepalived/keepalived.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
    mode: 0644
  register: keepalived_config
  become: yes
  tags:
    - keepalived
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/service_module.html
- name: Keepalived service
  service:
    name: keepalived
    state: restarted
    enabled: yes
  become: yes
  tags:
    - keepalived
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/template_module.html
# https://www.mydailytutorials.com/ansible-template-module-examples/
# https://jinja.palletsprojects.com/en/2.10.x/
- name: Template haproxy config file
  template:
    src: haproxy/haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    mode: 0644
  register: haproxy_config
  become: yes
  tags:
    - haproxy
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/service_module.html
- name: HAproxy service
  service:
    name: haproxy
    state: restarted
    enabled: yes
  become: yes
  tags:
    - haproxy
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/template_module.html
# https://www.mydailytutorials.com/ansible-template-module-examples/
# https://jinja.palletsprojects.com/en/2.10.x/
- name: Template rook config file
  template:
    src: rook/clean-rook.sh.j2
    dest: "/home/{{ ansible_user }}/clean-rook.sh"
    mode: 0700
    owner: root
    group: root
  become: yes
  tags:
    - rook
    - nucs

# https://docs.ansible.com/ansible/2.9/modules/import_tasks_module.html
# sombra specific tasks file for shokohscrole
- name: Sombra tasks
  import_tasks: sombra/sombra.yml
  when: ansible_facts['nodename']|lower == 'sombra'

# https://docs.ansible.com/ansible/2.9/modules/import_tasks_module.html
# lucio specific tasks file for shokohscrole
- name: Lucio tasks
  import_tasks: lucio/lucio.yml
  when: ansible_facts['nodename']|lower == 'lucio'

# https://docs.ansible.com/ansible/2.9/modules/import_tasks_module.html
# zarya specific tasks file for shokohscrole
- name: Zarya tasks
  import_tasks: zarya/zarya.yml
  when: ansible_facts['nodename']|lower == 'zarya'
