# probes tasks file for shokohscrole
# https://github.com/shokohsc/essbey
# https://github.com/prometheus/node_exporter
# https://github.com/google/cadvisor
---
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
# https://hub.docker.com/r/zcube/cadvisor
# https://github.com/google/cadvisor/issues/1236
- name: CAdvisor docker container
  docker_container:
    image: '{{ cadvisor_image }}'
    pull: true
    name: cadvisor
    hostname: cadvisor
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: '{{ docker_network }}'
    volumes:
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /:/rootfs:ro
    restart_policy: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:cadvisor.{{ ansible_facts['nodename'] }}.home"
      traefik.port: '8080'
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"

# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: NodeExporter docker container
  docker_container:
    image: quay.io/prometheus/node-exporter
    pull: true
    name: nodeexporter
    volumes:
      - /:/host:ro,rslave
    restart_policy: unless-stopped
    pid_mode: host
    network_mode: host
    command:
      - '--path.rootfs=/host'
    capabilities:
      - sys_time
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"

# https://docs.ansible.com/ansible/latest/modules/copy_module.html
- name: Copy filebeat configuration file
  copy:
    src: filebeat/
    dest: '/home/{{ ansible_user }}/filebeat/'

# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: Filebeat docker container
  docker_container:
    image: '{{ filebeat_image }}'
    pull: true
    name: filebeat
    restart_policy: unless-stopped
    hostname: "filebeat-{{ ansible_facts['nodename'] }}"
    networks_cli_compatible: yes
    user: root
    purge_networks: yes
    networks:
      - name: '{{ docker_network }}'
    command: '/usr/share/filebeat/filebeat -e -strict.perms=false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:ro
      - /home/{{ ansible_user }}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
