# traefik tasks file for shokohscrole
# https://docs.traefik.io/v1.7/
# https://github.com/containous/traefik
---
# https://docs.ansible.com/ansible/latest/modules/template_module.html
# https://www.mydailytutorials.com/ansible-template-module-examples/
# https://jinja.palletsprojects.com/en/2.10.x/
- name: Template traefik config file
  template:
    src: traefik/traefik.toml.j2
    dest: "/home/{{ ansible_user }}/traefik/traefik.toml"

# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html
- name: Traefik docker container
  docker_container:
    image: traefik:1.7.16-alpine
    name: traefik
    command: --metrics --metrics.prometheus
    hostname: traefik
    networks_cli_compatible: yes
    purge_networks: yes
    networks:
      - name: '{{ docker_network }}'
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/home/{{ ansible_user }}/traefik/:/etc/traefik/"
    restart_policy: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:traefik.{{ ansible_facts['nodename'] }}.home"
      traefik.port: '8080'
  vars:
    ansible_python_interpreter: "{{ '/usr/bin/env python-docker' }}"
